### ISSUE TITLE
x509: ECDSA verification failure

### ISSUE THREAD

**Issue by ercw** [onechain/fabric-explorer#14]
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.org1.example.com")
    at /home/ercw/go/src/github.com/hyperledger/fabric/examples/fabric-docker-compose-svt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
error: [Channel.js]: Failed Query block. Error: Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.org1.example.com")
    at /home/ercw/go/src/github.com/hyperledger/fabric/examples/fabric-docker-compose-svt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-08 09:05:29.591] [ERROR] Query - Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.org1.example.com")
    at /home/ercw/go/src/github.com/hyperledger/fabric/examples/fabric-docker-compose-svt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-08 09:05:29.591] [ERROR] blockscanner - TypeError: Cannot read property 'data' of undefined
    at EventEmitter.<anonymous> (/home/ercw/go/src/github.com/hyperledger/fabric/examples/fabric-docker-compose-svt/fabric-explorer/listener/blocklistener.js:14:30)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at saveBlockRange (/home/ercw/go/src/github.com/hyperledger/fabric/examples/fabric-docker-compose-svt/fabric-explorer/service/blockscanner.js:35:23)
    at next (native)
    at onFulfilled (/home/ercw/go/src/github.com/hyperledger/fabric/examples/fabric-docker-compose-svt/fabric-explorer/node_modules/co/index.js:65:19)

**Comment by ercw** [comment]
Please help with this error. I am running the default settings with TLS disabled.

{
   "host":"localhost",
   "port":"8080",
   "channelsList": ["mychannel"],
   "GOPATH":"../artifacts",
   "keyValueStore":"/tmp/fabric-client-kvs",
   "eventWaitTime":"30000",
   "enableTls":false,
   "users":[

**Comment by yoyokeen** [comment]
the same error come out and how to fix it?

**Comment by robertfeng1980** [comment]
You can try update the code.


Then  the config.json modify a property  “enableTls”  and set it value is true and try again


We suggest you can get the code from this url 

https://github.com/hyperledger/blockchain-explorer <https://github.com/hyperledger/blockchain-explorer>


Thank you !

**Comment by ercw** [comment]
Ok, I was able to run fabric-docker-compose-svt with TLS (this is not the default mode) enabled by manually changing start.sh to provide a -s option for ./network_setup.sh and setting environmental variable ENABLE_TLS=true.

Then did as you suggested but now I'm getting this error instead:

`Please open Internet explorer to access ：http://localhost:8080/
[2017-09-09 11:46:26.646] [DEBUG] metrics - [ 0, 0 ]
[2017-09-09 11:46:26.649] [DEBUG] metrics - [ 0, 0 ]
[2017-09-09 11:46:26.658] [DEBUG] mysqlservice -  the getRowsBySQlCase select count(1) c from chaincodes where channelname='mychannel' 
[2017-09-09 11:46:26.659] [DEBUG] mysqlservice -  the getRowsBySQlCase select max(blocknum) as blocknum from blocks  where channelname='mychannel'
[2017-09-09 11:46:26.668] [DEBUG] mysqlservice -  the getRowsBySQlCase select count(1) c from transaction where channelname='mychannel'
[2017-09-09 11:46:26.669] [DEBUG] mysqlservice -  the getRowsBySQlCase select max(blocknum) c from blocks where channelname='mychannel'
E0909 11:46:26.718498588   94300 ssl_transport_security.c:921] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Connect Failed
    at /home/ercw/go/src/github.com/hyperledger/fabric/examples/fabric-docker-compose-svt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
error: [Client.js]: Failed Installed Chaincodes Query. Error: Error: Connect Failed
    at /home/ercw/go/src/github.com/hyperledger/fabric/examples/fabric-docker-compose-svt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-09 11:46:26.723] [ERROR] Query - Error: Connect Failed
    at /home/ercw/go/src/github.com/hyperledger/fabric/examples/fabric-docker-compose-svt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-09 11:46:26.723] [DEBUG] blockscanner - Error: Connect Failed
    at /home/ercw/go/src/github.com/hyperledger/fabric/examples/fabric-docker-compose-svt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
E0909 11:46:26.734817073   94300 ssl_transport_security.c:921] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Connect Failed
    at /home/ercw/go/src/github.com/hyperledger/fabric/examples/fabric-docker-compose-svt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
error: [Channel.js]: Failed Query channel info. Error: Error: Connect Failed
    at /home/ercw/go/src/github.com/hyperledger/fabric/examples/fabric-docker-compose-svt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-09 11:46:26.735] [ERROR] Query - Error: Connect Failed
    at /home/ercw/go/src/github.com/hyperledger/fabric/examples/fabric-docker-compose-svt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-09 11:46:26.736] [DEBUG] Query - <<<<<<<<<< channel height >>>>>>>>>
[2017-09-09 11:46:26.736] [ERROR] blockscanner - TypeError: Cannot read property 'low' of undefined
    at getChainInfo.then.response (/home/ercw/go/src/github.com/hyperledger/fabric/examples/fabric-docker-compose-svt/fabric-explorer/app/query.js:242:32)
[2017-09-09 11:46:27.651] [DEBUG] metrics - [ 0, 0 ]
[2017-09-09 11:46:27.652] [DEBUG] metrics - [ 0, 0 ]
[2017-09-09 11:46:27.652] [DEBUG] mysqlservice -  the getRowsBySQlCase select count(1) c from chaincodes where channelname='mychannel'`

**Comment by robertfeng1980** [comment]
{
"host":"localhost",
"port":"8080",
"channelsList": ["mychannel"],
"GOPATH":"../artifacts",
"keyValueStore":"/tmp/fabric-client-kvs",
"eventWaitTime":"30000",
"enableTls":false,
"users”:[


You can try modify   property   “enableTls” to true , then try Reboot fabric-explorer again!

Thank you!

**Comment by ercw** [comment]
The error above is with "enableTls":true

**Comment by petonwu** [comment]
Hi Gurus,

Currently，I hit the following errors in using fabric-explorer to another sample, it is FabCar(fabric1.0 sample).Could you please help check what the cause is? thanks!
============================
[2017-10-11 16:21:09.722] [DEBUG] metrics - [ 0, 0 ]
[2017-10-11 16:21:09.723] [DEBUG] metrics - [ 0, 0 ]
[2017-10-11 16:21:09.723] [DEBUG] mysqlservice -  the getRowsBySQlCase select count(1) c from chaincodes where channelname='mychannel' 
[2017-10-11 16:21:09.724] [DEBUG] mysqlservice -  the getRowsBySQlCase select count(1) c from transaction where channelname='mychannel'
[2017-10-11 16:21:09.724] [DEBUG] mysqlservice -  the getRowsBySQlCase select max(blocknum) c from blocks where channelname='mychannel'
[2017-10-11 16:21:09.889] [ERROR] Helper - =============Peer=peer1
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.org1.example.com") at /root/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
error: [Client.js]: Failed Installed Chaincodes Query. Error: Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.org1.example.com") at /root/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-10-11 16:21:09.897] [ERROR] Query - Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.org1.example.com") at /root/fabric-explorer/no
...

The config of network-config.json is as below:
{
	"network-config": {
		"orderer": [{
			"url": "grpc://127.0.0.1:7050",
			"server-hostname": "orderer0.example.com"
		}
		],
		"org1": {
			"name": "peerOrg1",
			"mspid": "Org1MSP",
			"ca": "http://127.0.0.1:7054",
			"peer1": {
				"requests": "grpc://127.0.0.1:7051",
				"events": "grpc://127.0.0.1:7053",
				"server-hostname": "peer0.org1.example.com"
			},
			"admin": {
				"key": "/artifacts/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore",
				"cert": "/artifacts/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts"
			}
		}
	}
}

And the config.json is as below:
{
   "host":"localhost",
   "port":"8080",
   "channelsList": ["mychannel"],
   "GOPATH":"../artifacts",
   "keyValueStore":"/tmp/fabric-client-kvs2",
   "eventWaitTime":"30000",
   "enableTls":false,
   "users":[
      {
         "username":"admin",
         "secret":"adminpw"
      }
   ],
   "mysql":{
      "host":"127.0.0.1",
      "database":"fabricexplorer",
      "port":"3306",
      "username":"root",
      "passwd":""
   }
}

**Comment by csquan** [comment]
I have run into same error,had you fixed?

**Comment by du2016** [comment]
i have the same error too,

**Comment by dj-rapidqube** [comment]
try migrating your code to fabric samples v1.0.2 ..it was a bug in v1.0..
and run the code again...it would work..and do put tls to false in network config.

**Comment by ashish235** [comment]
Same error with 1.0.5 also.. it works in somtimes.. and then when I regenerate the certs, i get the same errors again.

**Comment by atif92** [comment]
same problem with 1.1 alfa

**Comment by vanderthiel** [comment]
Ok so I ran into this same problem and it cost me a couple of hours to figure out, for me this was caused by running generate.sh again to regenerate my artifacts, including the certificates. There is a setting in the docker-compose.yml for the ca.example.com service. It's called FABRIC_CA_SERVER_CA_KEYFILE and it must point to the newly generated certificate file name, since on regeneration the filename changed.

**Comment by tk1993** [comment]
I have changed the FABRIC_CA_SERVER_CA_KEYFILE with the generated artifacts of ca but still got the same error

POST /api/v1/register 401 26 "Untrusted certificate: Failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.epo1.epo.com")"

**Comment by coderintherye** [comment]
Another way this can happen is if the orderer container tries to start before the certificate authority container, you want to make sure that orderer.example.com has something like:
depends_on:
  ca.example.com
or in some other way ensure the orderer container starts after the CA
