### ISSUE TITLE
TypeError: Cannot read property 'low' of undefined

### ISSUE THREAD

**Issue by yoyokeen** [onechain/fabric-explorer#15]
[2017-09-12 11:15:57.002] [INFO] Helper - Successfully loaded member from persistence
[2017-09-12 11:15:57.007] [DEBUG] Helper - [crypto_ecdsa_aes]: ecdsa signature:  Signature {
  r: <BN: f692ed2a645e7a280ab5df645fec361c30ec73a26a61aa799bac3d554206ac1c>,
  s: <BN: 443f3ae9a5019abdbbbf3e478f67466b5cda08103c37a64f146231bbec484e71>,
  recoveryParam: 1 }
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority
    at /opt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
error: [Channel.js]: Failed Query channel info. Error: Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority
    at /opt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-12 11:15:57.012] [ERROR] Query - Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority
    at /opt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-12 11:15:57.012] [DEBUG] Query - <<<<<<<<<< channel height >>>>>>>>>
[2017-09-12 11:15:57.012] [ERROR] blockscanner - TypeError: Cannot read property 'low' of undefined

**Comment by yoyokeen** [comment]
[2017-09-12 11:15:26.944] [DEBUG] Helper - [ecdsa/key.js]: ECDSA curve param Y: 9d37eae137f328e09e34f0b077df681221cad87484507b97ab9598c67d16ed42
[2017-09-12 11:15:26.945] [DEBUG] Helper - [FileKeyValueStore.js]: FileKeyValueStore -- setValue
[2017-09-12 11:15:26.946] [INFO] Helper - Successfully loaded member from persistence
[2017-09-12 11:15:26.952] [DEBUG] Helper - [crypto_ecdsa_aes]: ecdsa signature:  Signature {
  r: <BN: ccf315d07cb33640679dd844438a86b59cb2c4d5cd177976bd78d2c77e863cd1>,
  s: <BN: 404988e98132068eadb628d318d293562900b65f17d74c3b59c18274ce0ad116>,
  recoveryParam: 0 }
[2017-09-12 11:15:26.965] [DEBUG] Helper - admin failed to register
[2017-09-12 11:15:26.966] [ERROR] Helper - admin enrollment failed

**Comment by yoyokeen** [comment]
"users":[
      {
         "username":"admin",
         "secret":"adminpw"
      }
   ],

**Comment by robertfeng1980** [comment]
hi

You can find  config.json   then set enableTls value is true  and try it again!

**Comment by yoyokeen** [comment]
yes.
"enableTls":true
but, the error already come out.

**Comment by yoyokeen** [comment]
the same error:
[2017-09-12 12:15:55.668] [DEBUG] Helper - [crypto_ecdsa_aes]: ecdsa signature:  Signature {
  r: <BN: 5f3a5870853fa4f8ec5d2b47733444945e7cc62ab73ee42868ee6c43d9d49a8b>,
  s: <BN: 700d6f0e37188f7cfd82f02ef6ced8c05adc7044709ffce26ba3ff51f5c50d3b>,
  recoveryParam: 1 }
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Connect Failed
    at /opt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
error: [Channel.js]: Failed Query channel info. Error: Error: Connect Failed
    at /opt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-12 12:15:55.673] [ERROR] Query - Error: Connect Failed
    at /opt/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-12 12:15:55.673] [DEBUG] Query - <<<<<<<<<< channel height >>>>>>>>>
[2017-09-12 12:15:55.674] [ERROR] blockscanner - TypeError: Cannot read property 'low' of undefined

**Comment by robertfeng1980** [comment]
If can me review you  docker  ps

**Comment by yoyokeen** [comment]
our blockchain platform running, because our sdk  work well.

**Comment by yoyokeen** [comment]
our blockchain platform is running, because our sdk work well.

**Comment by yoyokeen** [comment]
![image](https://user-images.githubusercontent.com/11547958/30309706-4b7a69c2-97bf-11e7-903b-1864f83c7c4e.png)

**Comment by yoyokeen** [comment]
our platform have been distributed on six hosts, so I need pick up all of the info(docker ps -a)?

**Comment by robertfeng1980** [comment]
Yes  docker ps 


Thank you

**Comment by yoyokeen** [comment]
docker ps -a
CONTAINER ID        IMAGE                        COMMAND             CREATED             STATUS              PORTS               NAMES
4f6c6d5c8013        hyperledger/fabric-orderer   "orderer"           2 days ago          Up 2 days                               orderer0.example.com

docker ps -a
CONTAINER ID        IMAGE                        COMMAND             CREATED             STATUS              PORTS               NAMES
671de46baf8a        hyperledger/fabric-orderer   "orderer"           2 days ago          Up 2 days                               orderer1.example.com

docker ps -a
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS                    PORTS               NAMES
8975da771879        dev-peer0.org1.example.com-po1_go-1      "chaincode -peer.a..."   3 hours ago         Up 3 hours                                    dev-peer0.org1.example.com-po1_go-1
6927dd86c105        dev-peer0.org1.example.com-auth_go-1      "chaincode -peer.a..."   5 hours ago         Up 5 hours                                    dev-peer0.org1.example.com-auth_go-1
a01b068f66ea        dev-peer0.org1.example.com-po_go-1       "chaincode -peer.a..."   5 hours ago         Up 5 hours                                    dev-peer0.org1.example.com-po_go-1
296cbb1001d3        dev-peer0.org1.example.com-com_go-1   "chaincode -peer.a..."   2 days ago          Up 2 days                                     dev-peer0.org1.example.com-com_go-1
84c7087019be        dev-peer0.org1.example.com-mycc-1.0       "chaincode -peer.a..."   2 days ago          Exited (2) 2 days ago                         dev-peer0.org1.example.com-mycc-1.0
69e89221cc04        hyperledger/fabric-tools                  "/bin/bash -c './s..."   2 days ago          Exited (137) 2 days ago                       cli
f744f8b299a8        hyperledger/fabric-peer                   "peer node start"        2 days ago          Up 2 days                                     peer0.org1.example.com

docker ps -a
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                    PORTS               NAMES
a7a21577b7d0        dev-peer0.org2.example.com-mycc-1.0   "chaincode -peer.a..."   2 days ago          Exited (2) 2 days ago                         dev-peer0.org2.example.com-mycc-1.0
c6411add6c8e        hyperledger/fabric-tools              "/bin/bash -c './s..."   2 days ago          Exited (137) 2 days ago                       cli
b6ee29bce672        hyperledger/fabric-peer               "peer node start"        2 days ago          Up 2 days                                     peer0.org2.example.com

**Comment by robertfeng1980** [comment]
where CA？




At 2017-09-14 13:34:33, "yoyokeen" <notifications@github.com> wrote:


docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
4f6c6d5c8013 hyperledger/fabric-orderer "orderer" 2 days ago Up 2 days orderer0.example.com

docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
671de46baf8a hyperledger/fabric-orderer "orderer" 2 days ago Up 2 days orderer1.example.com

docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
8975da771879 dev-peer0.org1.example.com-po1_go-1 "chaincode -peer.a..." 3 hours ago Up 3 hours dev-peer0.org1.example.com-po1_go-1
6927dd86c105 dev-peer0.org1.example.com-auth_go-1 "chaincode -peer.a..." 5 hours ago Up 5 hours dev-peer0.org1.example.com-auth_go-1
a01b068f66ea dev-peer0.org1.example.com-po_go-1 "chaincode -peer.a..." 5 hours ago Up 5 hours dev-peer0.org1.example.com-po_go-1
296cbb1001d3 dev-peer0.org1.example.com-com_go-1 "chaincode -peer.a..." 2 days ago Up 2 days dev-peer0.org1.example.com-com_go-1
84c7087019be dev-peer0.org1.example.com-mycc-1.0 "chaincode -peer.a..." 2 days ago Exited (2) 2 days ago dev-peer0.org1.example.com-mycc-1.0
69e89221cc04 hyperledger/fabric-tools "/bin/bash -c './s..." 2 days ago Exited (137) 2 days ago cli
f744f8b299a8 hyperledger/fabric-peer "peer node start" 2 days ago Up 2 days peer0.org1.example.com

docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
a7a21577b7d0 dev-peer0.org2.example.com-mycc-1.0 "chaincode -peer.a..." 2 days ago Exited (2) 2 days ago dev-peer0.org2.example.com-mycc-1.0
c6411add6c8e hyperledger/fabric-tools "/bin/bash -c './s..." 2 days ago Exited (137) 2 days ago cli
b6ee29bce672 hyperledger/fabric-peer "peer node start" 2 days ago Up 2 days peer0.org2.example.com

**Comment by yoyokeen** [comment]
docker ps -a
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                    PORTS                    NAMES
f2bb51b1d1fa        fabric-ca:lastest                     "sh -c 'fabric-ca-..."   3 minutes ago       Up 3 minutes              0.0.0.0:7054->7054/tcp   fabric-ca-server
a7a21577b7d0        dev-peer0.org2.example.com-mycc-1.0   "chaincode -peer.a..."   3 days ago          Exited (2) 3 days ago                              dev-peer0.org2.example.com-mycc-1.0
c6411add6c8e        hyperledger/fabric-tools              "/bin/bash -c './s..."   3 days ago          Exited (137) 3 days ago                            cli
b6ee29bce672        hyperledger/fabric-peer               "peer node start"        3 days ago          Up 3 days                                          peer0.org2.example.com


docker ps -a
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS                    PORTS                    NAMES
101696f3190c        fabric-ca:lastest                         "sh -c 'fabric-ca-..."   6 minutes ago       Up 6 minutes              0.0.0.0:7054->7054/tcp   fabric-ca-server
296cbb1001d3        dev-peer0.org1.example.com-company_go-1   "chaincode -peer.a..."   3 days ago          Up 3 days                                          dev-peer0.org1.example.com-company_go-1
84c7087019be        dev-peer0.org1.example.com-mycc-1.0       "chaincode -peer.a..."   3 days ago          Exited (2) 3 days ago                              dev-peer0.org1.example.com-mycc-1.0
69e89221cc04        hyperledger/fabric-tools                  "/bin/bash -c './s..."   3 days ago          Exited (137) 3 days ago                            cli
f744f8b299a8        hyperledger/fabric-peer                   "peer node start"        3 days ago          Up 3 days                                          peer0.org1.example.com

**Comment by yoyokeen** [comment]
I just start CA. but test it with error still. I havent config tls on CA.because havent to know how to do it.Can u point me in it?

**Comment by yoyokeen** [comment]
I re-install a new env.

**Comment by yoyokeen** [comment]
docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                        PORTS                                            NAMES
2dd4d36b3ffe        hyperledger/fabric-peer      "peer node start"        14 minutes ago      Up 14 minutes                 0.0.0.0:8056->7051/tcp, 0.0.0.0:8058->7053/tcp   peer1.org2.example.com
35663f0370ff        hyperledger/fabric-peer      "peer node start"        14 minutes ago      Up 14 minutes                 0.0.0.0:7056->7051/tcp, 0.0.0.0:7058->7053/tcp   peer1.org1.example.com
fca70f40941b        hyperledger/fabric-peer      "peer node start"        14 minutes ago      Up 14 minutes                 0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp   peer0.org1.example.com
dce32547bd78        hyperledger/fabric-peer      "peer node start"        14 minutes ago      Up 14 minutes                 0.0.0.0:8051->7051/tcp, 0.0.0.0:8053->7053/tcp   peer0.org2.example.com
7e655f7b4180        hyperledger/fabric-ca        "sh -c 'fabric-ca-..."   14 minutes ago      Up 14 minutes                 0.0.0.0:8054->7054/tcp                           ca_peerOrg2
e05d8eb99d49        hyperledger/fabric-tools     "/bin/bash /opt/bi..."   14 minutes ago      Exited (127) 14 minutes ago                                                    configtxlator
c8aa92e16dbe        hyperledger/fabric-ca        "sh -c 'fabric-ca-..."   14 minutes ago      Up 14 minutes                 0.0.0.0:7054->7054/tcp                           ca_peerOrg1
ed2b1a28f83b        hyperledger/fabric-orderer   "orderer"                14 minutes ago      Up 14 minutes                 0.0.0.0:7050->7050/tcp                           orderer.example.com
6a7f5185d4d5        hyperledger/fabric-ccenv     "/bin/bash"              14 minutes ago      Exited (0) 14 minutes ago                                                      sdkintegration_ccenv_1

**Comment by yoyokeen** [comment]
[2017-09-19 09:01:58.313] [DEBUG] Helper - [crypto_ecdsa_aes]: ecdsa signature:  Signature {
  r: <BN: 9ab6118ba247bac9c201611c11d0ce68169dcb62bfa3605f61c6450f0a614450>,
  s: <BN: 1ffee8abfa4d4b6f0d806ece03cd52d6cbded539fd67c16a84d212d79ce23d09>,
  recoveryParam: 1 }
E0919 09:01:58.315371358   28931 ssl_transport_security.c:921] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Connect Failed
    at /opt/fe/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
error: [Client.js]: Failed Installed Chaincodes Query. Error: Error: Connect Failed
    at /opt/fe/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-19 09:01:58.316] [ERROR] Query - Error: Connect Failed
    at /opt/fe/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-19 09:01:58.316] [DEBUG] blockscanner - Error: Connect Failed
    at /opt/fe/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
E0919 09:01:58.318455171   28931 ssl_transport_security.c:921] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Connect Failed
    at /opt/fe/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
error: [Channel.js]: Failed Query channel info. Error: Error: Connect Failed
    at /opt/fe/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-19 09:01:58.320] [ERROR] Query - Error: Connect Failed
    at /opt/fe/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-19 09:01:58.320] [DEBUG] Query - <<<<<<<<<< channel height >>>>>>>>>
[2017-09-19 09:01:58.321] [ERROR] blockscanner - TypeError: Cannot read property 'low' of undefined
    at getChainInfo.then.response (/opt/fe/fabric-explorer/app/query.js:242:32)

**Comment by yoyokeen** [comment]
E0919 09:17:19.534281117   29155 ssl_transport_security.c:921] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Connect Failed
    at /opt/fe/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
error: [Client.js]: Failed Installed Chaincodes Query. Error: Error: Connect Failed
    at /opt/fe/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-19 09:17:19.535] [ERROR] Query - Error: Connect Failed
    at /opt/fe/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-19 09:17:19.535] [DEBUG] blockscanner - Error: Connect Failed
    at /opt/fe/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
E0919 09:17:19.537397962   29155 ssl_transport_security.c:921] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Connect Failed
    at /opt/fe/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
error: [Channel.js]: Failed Query channel info. Error: Error: Connect Failed
    at /opt/fe/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-19 09:17:19.538] [ERROR] Query - Error: Connect Failed
    at /opt/fe/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-19 09:17:19.538] [DEBUG] Query - <<<<<<<<<< channel height >>>>>>>>>
[2017-09-19 09:17:19.538] [DEBUG] Query - Error: Connect Failed
    at /opt/fe/fabric-explorer/node_modules/grpc/src/node/src/client.js:554:15
[2017-09-19 09:17:19.539] [ERROR] blockscanner - TypeError: Cannot read property 'low' of undefined
    at getChainInfo.then.response (/opt/fe/fabric-explorer/app/query.js:243:32)
^C

**Comment by yoyokeen** [comment]
now, it's OK.

**Comment by karthikbabuks** [comment]
@yoyokeen Am encountering the same error can you share the solution. My setup is non-tls and I can query the chaincode using java sdk but it is not working for fabric explorer

`[client-utils.js]: sendPeersProposal - Promise is rejected: Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority`

Am using fabcar example.

**Comment by robertfeng1980** [comment]
Can you show me your app/network-config.json?

Thank you !

**Comment by karthikbabuks** [comment]
````
{
   "host":"localhost",
   "port":"8080",
   "channelsList": ["mychannel"],
   "GOPATH":"../artifacts",
        "keyValueStore":"/tmp/fabric-client-kvs",
   "enableTls":false,
   "users":[
      {
         "username":"admin",
         "secret":"adminpw"
      }
   ],
   "mysql":{
      "host":"127.0.0.1",
      "port":"3306",
      "database":"fabricexplorer",
      "username":"root",
      "passwd":"xxxxx"
   }
}
````
I tried with IP and lo but nothing helps.

Docker output

CONTAINER ID        IMAGE                                                                                                    COMMAND                  CREATED             STATUS              PORTS                                            NAMES
9a566605f5cf        dev-peer0.org1.example.com-fabcar-1.0-5c906e402ed29f20260ae42283216aa75549c571e2e380f3615826365d8269ba   "chaincode -peer.a..."   12 hours ago        Up 12 hours                                                          dev-peer0.org1.example.com-fabcar-1.0
7e487d0dc2be        hyperledger/fabric-tools                                                                                 "/bin/bash"              12 hours ago        Up 12 hours                                                          cli
9c30193844bc        hyperledger/fabric-peer                                                                                  "peer node start"        12 hours ago        Up 12 hours         0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp   peer0.org1.example.com
2ea9bfcf348d        hyperledger/fabric-couchdb                                                                               "tini -- /docker-e..."   12 hours ago        Up 12 hours         4369/tcp, 9100/tcp, 0.0.0.0:5984->5984/tcp       couchdb
fd70c6fc3514        hyperledger/fabric-ca                                                                                    "sh -c 'fabric-ca-..."   12 hours ago        Up 12 hours         0.0.0.0:7054->7054/tcp                           ca.example.com
dd097d973410        hyperledger/fabric-orderer                                                                               "orderer"                12 hours ago        Up 12 hours         0.0.0.0:7050->7050/tcp                           orderer.example.com

**Comment by robertfeng1980** [comment]
You can set  "enableTls”:true and try it again!

Thanks

**Comment by mobinauten** [comment]
How did you solve this issue, I have the same problem:

`Please open Internet explorer to access ：http://localhost:8080/
[2017-11-08 08:21:44.913] [ERROR] Helper - Error: Calling enrollment endpoint failed with error [Error: write EPROTO 140390073870400:error:1411713E:SSL routines:ssl_check_srvr_ecc_cert_and_alg:ecc cert n
ot for signing:ssl_lib.c:2512:
140390073870400:error:14082130:SSL routines:ssl3_check_cert_and_algorithm:bad ecc cert:s3_clnt.c:3546:
]
    at ClientRequest.<anonymous> (/home/osboxes/dev/fabric-samples/blockchain-explorer/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:711:12)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:343:10)
    at onwrite (_stream_writable.js:361:5)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at fireErrorCallbacks (net.js:467:13)
[2017-11-08 08:21:44.914] [ERROR] Helper - admin enrollment failed
(node:1001) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot save null userContext.
[2017-11-08 08:21:45.076] [ERROR] Helper - Error: Calling enrollment endpoint failed with error [Error: write EPROTO 140390073870400:error:1411713E:SSL routines:ssl_check_srvr_ecc_cert_and_alg:ecc cert n
ot for signing:ssl_lib.c:2512:
140390073870400:error:14082130:SSL routines:ssl3_check_cert_and_algorithm:bad ecc cert:s3_clnt.c:3546:
]
    at ClientRequest.<anonymous> (/home/osboxes/dev/fabric-samples/blockchain-explorer/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:711:12)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:343:10)
    at onwrite (_stream_writable.js:361:5)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at fireErrorCallbacks (net.js:467:13)
[2017-11-08 08:21:45.076] [ERROR] Helper - admin enrollment failed
[2017-11-08 08:21:45.077] [ERROR] Query - Error: Missing userContext parameter
    at new TransactionID (/home/osboxes/dev/fabric-samples/blockchain-explorer/node_modules/fabric-client/lib/TransactionID.js:43:10)
    at Channel.queryBlock (/home/osboxes/dev/fabric-samples/blockchain-explorer/node_modules/fabric-client/lib/Channel.js:905:14)
    at helper.getRegisteredUsers.then (/home/osboxes/dev/fabric-samples/blockchain-explorer/app/query.js:91:18)
[2017-11-08 08:21:45.078] [ERROR] blockscanner - TypeError: Cannot read property 'data' of undefined
`

**Comment by Adesh** [comment]
Truncate the blocks & transactions tables from fabricexplorer database (i used mysql workbench), and it will work like a charm.

**Comment by gantleman** [comment]
i am too!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Please open Internet explorer to access ：http://localhost:8080/
^[[36m[2017-11-18 19:03:29.099] [DEBUG] metrics - ^[[39m[ 0, 0 ]
^[[36m[2017-11-18 19:03:29.103] [DEBUG] metrics - ^[[39m[ 0, 0 ]
^[[36m[2017-11-18 19:03:29.113] [DEBUG] mysqlservice - ^[[39m the getRowsBySQlCase select count(1) $
^[[36m[2017-11-18 19:03:29.119] [DEBUG] mysqlservice - ^[[39m the getRowsBySQlCase select max(block$
^[[36m[2017-11-18 19:03:29.121] [DEBUG] mysqlservice - ^[[39m the getRowsBySQlCase select count(1) $
^[[36m[2017-11-18 19:03:29.128] [DEBUG] mysqlservice - ^[[39m the getRowsBySQlCase select max(block$
^[[31m[2017-11-18 19:03:29.274] [ERROR] Helper - ^[[39mError: Calling enrollment endpoint failed wi$
140186663958592:error:14082130:SSL routines:ssl3_check_cert_and_algorithm:bad ecc cert:s3_clnt.c:35$
]
    at ClientRequest.<anonymous> (/root/solution-blockchain-demo/blockchain-explorer/node_modules/f$
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:343:10)
    at onwrite (_stream_writable.js:361:5)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at fireErrorCallbacks (net.js:467:13)
^[[31m[2017-11-18 19:03:29.275] [ERROR] Helper - ^[[39madmin enrollment failed
(node:23032) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error$
^[[36m[2017-11-18 19:03:29.296] [DEBUG] Query - ^[[39m===========================================
^[[36m[2017-11-18 19:03:29.296] [DEBUG] Query - ^[[39mByteBuffer {
  buffer: <Buffer 08 04 12 20 56 7f e0 11 0e c3 cb 2e ae 04 1d 16 62 21 6a 05 8b 59 c0 e0 ac 53 5c $
  offset: 4,
  markedOffset: -1,
  limit: 36,
  littleEndian: true,
  noAssert: false }

**Comment by gantleman** [comment]
config.json 

{
    "host":"localhost",
    "port":"8080",
    "channelsList": ["mychannel"],
    "GOPATH":"../artifacts",
    "keyValueStore":"/tmp/fabric-client-kvs",
    "eventWaitTime":"300000",
    "enableTls":true,
    "users":[
       {
          "username":"admin",
          "secret":"adminpw"
       }
    ],
   "mysql":{
      "host":"127.0.0.1",
      "port":"3306",
      "database":"fabricexplorer",
      "username":"root",
      "passwd":"123455"
   }
 }
