### ISSUE TITLE
Not able to start the application

### ISSUE THREAD

**Issue by vu3mmg** [onechain/fabric-explorer#2]
Hi ,
I am not able to start the application . I gave correct user name and password for mysql .
Is there any other logs I could see .

Please see the log.log file output 

  the getRowsBySQlCase select count(1) c from chaincodes where channelname='mychannel' 
/Users/maheshgovind/go/fabric-explorer/db/mysqlservice.js:490
            if( rows.length == 0 )
                    ^

TypeError: Cannot read property 'length' of undefined
    at Query._callback (/Users/maheshgovind/go/fabric-explorer/db/mysqlservice.js:490:21)
    at Query.Sequence.end (/Users/maheshgovind/go/fabric-explorer/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /Users/maheshgovind/go/fabric-explorer/node_modules/mysql/lib/protocol/Protocol.js:399:18
    at Array.forEach (native)
    at /Users/maheshgovind/go/fabric-explorer/node_modules/mysql/lib/protocol/Protocol.js:398:13
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by nerd010** [comment]
when i try to run the application, i am not able to start the application.
the error is 

^[[36m[2017-07-13 19:51:21.420] [DEBUG] metrics - ^[[39m[ 0, 0 ]
^[[36m[2017-07-13 19:51:21.424] [DEBUG] metrics - ^[[39m[ 0, 0 ]
^[[36m[2017-07-13 19:51:21.446] [DEBUG] mysqlservice - ^[[39m the getRowsBySQlCase select count(1) c from chaincodes where channelname='mychannel'
/root/gocode/src/github.com/hyperledger/fabric-explorer/db/mysqlservice.js:491
            if( rows.length == 0 )
                    ^

TypeError: Cannot read property 'length' of undefined
    at Query._callback (/root/gocode/src/github.com/hyperledger/fabric-explorer/db/mysqlservice.js:491:21)
    at Query.Sequence.end (/root/gocode/src/github.com/hyperledger/fabric-explorer/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at /root/gocode/src/github.com/hyperledger/fabric-explorer/node_modules/mysql/lib/protocol/Protocol.js:399:18
    at Array.forEach (native)
    at /root/gocode/src/github.com/hyperledger/fabric-explorer/node_modules/mysql/lib/protocol/Protocol.js:398:13
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

please fix the error

**Comment by robertfeng1980** [comment]
we are modify database modify script , you can run and try it .

**Comment by robertfeng1980** [comment]
The bug has been fixed. You can gti pull

**Comment by nerd010** [comment]
出现这个问题的原因是什么？
