### ISSUE TITLE
No identity has been assigned to this client

### ISSUE THREAD

**Issue by paulsimon99** [onechain/fabric-explorer#21]
When trying to get channels via REST API by: curl http://localhost:8080/apis/channels?peer=peer1

I ran into the error:
---
Error: No identity has been assigned to this client
    at Client._getSigningIdentity (/home/ec2-user/fabric-explorer/node_modules/fabric-client/lib/Client.js:1206:11)
    at Client.queryChannels (/home/ec2-user/fabric-explorer/node_modules/fabric-client/lib/Client.js:827:23)
    at helper.getRegisteredUsers.then (/home/ec2-user/fabric-explorer/app/query.js:269:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Can you advise how to fix the issue? Thanks

**Comment by pradeepsama** [comment]
i am also facing this issue.
plz,let me know are u find the solution@paulsimon99

**Comment by avkkiran** [comment]
Please check the below link, might be useful to you.

https://stackoverflow.com/questions/52536257/no-identity-error-in-hyperledger-fabric/55686825#55686825
