### ISSUE TITLE
[ERROR] Query - Error: Missing userContext parameter

### ISSUE THREAD

**Issue by Preetam007** [onechain/fabric-explorer#22]
Running Hyperledger Blockchain Explorer in Ubuntu 16.04, I am getting the following error 

The browser is blank. after couple of messages like preparing explorer Accessing Network, Connecting Channel, Adding Blocks messages. However the fabricexplorer database connection SQL queries is resulting the correct details

Configuration :

Node.Js - v8.9.4

PostgreSQL - 9.5.12

Docker - 17.12.0-ce

docker-compose - 1.13.0, build 1719ceb

```
   [2018-04-13 10:24:35.703] [ERROR] Query - Error: Missing userContext parameter
    at new TransactionID (/home/utkarsh/blockchain-explorer/node_modules/fabric-client/lib/TransactionID.js:43:10)
    at Channel.queryInfo (/home/utkarsh/blockchain-explorer/node_modules/fabric-client/lib/Channel.js:765:14)
    at helper.getOrgAdmin.then (/home/utkarsh/blockchain-explorer/app/query.js:98:18)
    at <anonymous>
[2018-04-13 10:24:35.711] [ERROR] blockscanner - TypeError: Cannot read property 'low' of undefined
    at getChainInfo.then.response (/home/utkarsh/blockchain-explorer/app/query.js:213:24)
    at <anonymous>

```

**Comment by Preetam007** [comment]
[](url)
