### ISSUE TITLE
接入自己网络遇到问题 TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by ashk012** [onechain/fabric-explorer#25]
postgres://postgres:password@127.0.0.1:5432/fabricexplorer
(node:6272) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at Platform.setChannels (/home/skyhuihui/go/src/github.com/hyperledger/blockchain-explorer/app/platform/fabric/Platform.js:192:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:6272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by EurusLiao** [comment]
请问这个问题怎么解决？
