### ISSUE TITLE
Can't start the demo. An certificate error occurs

### ISSUE THREAD

**Issue by warm3snow** [onechain/fabric-explorer#6]
```
请在浏览器访问：http://localhost:9080/
[2017-07-21 10:29:03.776] [DEBUG] metrics - [ 0, 0 ]
[2017-07-21 10:29:03.785] [DEBUG] metrics - [ 0, 0 ]
[2017-07-21 10:29:04.073] [DEBUG] mysqlservice -  the getRowsBySQlCase select count(1) c from chaincodes where channelname='mychannel' 
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.org1.example.com")
    at /home/xxx/gopath/src/github.com/onechain/fabric-explorer/node_modules/grpc/src/node/src/client.js:434:17
error: [Client.js]: Failed Installed Chaincodes Query. Error: Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.org1.example.com")
    at /home/xxx/gopath/src/github.com/onechain/fabric-explorer/node_modules/grpc/src/node/src/client.js:434:17
[2017-07-21 10:29:04.118] [ERROR] Query - Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.org1.example.com")
    at /home/xxx/gopath/src/github.com/onechain/fabric-explorer/node_modules/grpc/src/node/src/client.js:434:17
[2017-07-21 10:29:04.119] [DEBUG] blockscanner - Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.org1.example.com")
    at /home/xxx/gopath/src/github.com/onechain/fabric-explorer/node_modules/grpc/src/node/src/client.js:434:17
[2017-07-21 10:29:04.157] [DEBUG] mysqlservice -  the getRowsBySQlCase select max(blocknum) as blocknum from blocks  where channelname='mychannel'
[2017-07-21 10:29:04.179] [DEBUG] mysqlservice -  the getRowsBySQlCase select count(1) c from transaction where channelname='mychannel'
[2017-07-21 10:29:04.181] [DEBUG] mysqlservice -  the getRowsBySQlCase select max(blocknum) c from blocks where channelname='mychannel'
[2017-07-21 10:29:04.750] [ERROR] Helper - admin enrollment failed
[2017-07-21 10:29:04.769] [DEBUG] Query - ===========================================
[2017-07-21 10:29:04.769] [DEBUG] Query - ByteBuffer {
  buffer: <Buffer 08 05 12 20 b5 2a f4 e4 c0 76 9e 4a 78 54 4f 24 e8 09 13 34 1b 3b eb 0b a1 5d de 69 de 34 34 25 cc 49 88 64 1a 20 d5 1d 45 70 13 dc 38 ad 51 df 87 8f ... >,
  offset: 4,
  markedOffset: -1,
  limit: 36,
  littleEndian: true,
  noAssert: false }
[2017-07-21 10:29:04.771] [DEBUG] Query - ===========================================
```

**Comment by robertfeng1980** [comment]
you can close fabric TLS , then restart server try it !

**Comment by warm3snow** [comment]
I have disabled the TLS, but still have the problem.

**Comment by v1pka** [comment]
I have the same issue for fabric basic-network example. 
It can't connect to peer node with reason:
> returned x509: certificate signed by unknown authority

**Comment by shenchao0120** [comment]
I have exactly  the same issue, and I tried it for  2 times still the same error.

**Comment by warm3snow** [comment]
Did anyone solve this problem?  I was stuck here for several days.

**Comment by qiushaoxi** [comment]
i change for tls connection. you can try my fork

**Comment by michielmulders** [comment]
Any updates on this issue? Getting this in examples with HLFv1.1? When I execute the query all commando in the docker container itself, I get the expected results. But when using the query.js script, it fails as it uses the user1 certificate (when using docker exec I use admin cert).

**Comment by vanderthiel** [comment]
Just check when you regenerate your certificates, in the docker-compose.yml, update the filename for the CA certificate. It changes when you regenerate your certificates

**Comment by tk1993** [comment]
I have changed the FABRIC_CA_SERVER_CA_KEYFILE with the generated artifacts of ca but still got the same error

POST /api/v1/register 401 26 "Untrusted certificate: Failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.epo1.epo.com")"

**Comment by mkumarceg** [comment]
i am also trying to add node sdk for my fabric multi host application. When i am trying to query/invoke using the node sdk facing the same error.  As mentioned below,

error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority
at new createStatusError (/scratch/node_SDK/fabric-test/nodejs/node_modules/grpc/src/client.js:64:15)
at /scratch/node_SDK/fabric-test/nodejs/node_modules/grpc/src/client.js:583:15

Is anybody resolved this error means, kindly post the solution here for reference.

**Comment by Macaret** [comment]
Any update on this issue?
